esphome:
  name: feeding-camera
  friendly_name: feeding-camera

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "DMOluU8JUMQ8MDYaTvke/0eiawNSa5Ivxh+A13MYSWQ="

ota:
  - platform: esphome
    password: "8c3192f942aa4b1c95197979bf693561"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Feeding-Monitor Fallback Hotspot"
    password: "Xth2g5fRjDRL"

i2c:
  id: i2c_cam
  sda: 26
  scl: 27

esp32_camera:
  name: ESP32 Cam
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_id: i2c_cam
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  vertical_flip: false
  resolution: 640x480

psram:

switch:
  - platform: gpio
    name: "Flashlight"
    pin:
      number: GPIO4

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot